#!/bin/bash -xe
yum update -y aws-cfn-bootstrap
# Install the files and packages from the metadata
/opt/aws/bin/cfn-init -v          --stack DevOps2         --resource WebServerInstance          --configsets Install          --region us-east-1
git clone https://github.com/HansPetrie/DevOps.git
cd DevOps
./install.sh
